### ISSUE TITLE
How to use action_cable_client in consumer Rails app

### ISSUE THREAD

**Issue by seyyah** [NullVoxPopuli/action_cable_client#15]
We want to interact a rails client/consumer app with other Rails' ActionCable server. How to use the action_cable_client for this purpose?

**Comment by NullVoxPopuli** [comment]
can you talk a little more about the use case around how you want to design your cable connections?

currently, action_cable_client acts as a single user, so keep that in mind :-)

**Comment by seyyah** [comment]
We want to use/consume the multiple rails actioncable/websocket servers in one rails app.

**Comment by seyyah** [comment]
For example,

- ws://server1.com:3000/cable
- ws://server2.com/cable

In rails app,

```ruby
  uri1 = "ws://server1.com:3000/cable/"
  client1 = ActionCableClient.new(uri1, 'RoomChannel')

  uri2 = "ws://server2.com:3000/cable/"
  client2 = ActionCableClient.new(uri2, 'ChatChannel')
  ...
```

**Comment by NullVoxPopuli** [comment]
ah ok. I think that's doable. 
I think you'd maybe want to run it in a different process, though -- since most of rails isn't evented.

**Comment by seyyah** [comment]
Thank you very much. I think to use to sinatra (but for new area). I found [example code](https://github.com/stewart/eventmachine-websockets-demo/blob/master/app.rb).

I write below pseudo code, but not test.

```ruby
require 'thin'
require 'action_cable_client'
require 'sinatra/base'

EM.run do
  class App < Sinatra::Base
    get '/' do
      erb :index
    end
  end

  uri1 = "ws://localhost:3001/cable/"
  client1 = ActionCableClient.new(uri1, 'RoomChannel')

  uri2 = "ws://localhost:3002/cable/"
  client2 = ActionCableClient.new(uri2, 'ChatChannel')

  ...

  App.run! :port => 3000
end
```

**Comment by seyyah** [comment]
These code is very well for us. We test for websocket-eventmachine-server and websocket-eventmachine-client, as soon as we try to action_cable_client.

```ruby
# app.rb
require 'thin'
require 'sinatra/base'
require 'eventmachine'
require 'websocket-eventmachine-server'
require 'websocket-eventmachine-client'
 
EM.epoll
EM.run do
  class App < Sinatra::Base
    get '/' do
      erb :index
    end
  end
  
  @clients = []
 
  WebSocket::EventMachine::Server.start(host: "localhost", port: 3001) do |ws|
    ws.onopen do |handshake|
      @clients << ws
      ws.send "Connected to #{handshake.path}."
    end
 
    ws.onclose do
      ws.send "Closed."
      @clients.delete ws
    end
 
    ws.onmessage do |msg|
      puts "Received Message: #{msg}"
     
      @clients.each do |socket|
        socket.send msg
      end
    end
  end

  wss   = WebSocket::EventMachine::Client.connect(uri: "ws://localhost:3001");
  wsc1 = WebSocket::EventMachine::Client.connect(uri: "ws://localhost:3011");
  wsc2 = WebSocket::EventMachine::Client.connect(uri: "ws://localhost:3012");

  wsc1.onopen do
    puts "wsc1: opopen"
    wss.send "wsc1 opened"
  end

  wsc1.onmessage do |msg, type|
    puts "wsc1: onmessage"
    wss.send "wsc1 message: #{msg}"
  end

  wsc2.onopen do
    puts "wsc2: opopen"
    wss.send "wsc2 opened"
  end

  wsc2.onmessage do |msg, type|
    puts "wsc2: onmessage"
    wss.send "wsc2 message: #{msg}"
  end
  
  App.run! bind: 'localhost', port: 3000
end
```

```html
<!-- views/index.erb -->
  <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
  <script>
    function addMessage(msg) {
      $("#log").append("<p>" + msg + "</p>");
    }
    
    socket = new WebSocket("ws://localhost:3001");
    socket.onopen = function() {
      addMessage("Socket Status: " + socket.readyState + " (open)");
    }
 
    socket.onclose = function() {
      addMessage("Socket Status: " + socket.readyState + " (closed)");
    }
 
    socket.onmessage = function(msg) {
      addMessage("Received: " + msg.data);
    }
  </script>

<div id="log"></div>
```

Our important addressess/uri are,

- Webserver: `http://localhost:3000`
- Main websocket server: `http://localhost:3001`
- Aux1 websocket server: `http://localhost:3011`
- Aux2 websocket server: `http://localhost:3012`

**Comment by NullVoxPopuli** [comment]
neat, I didn't think you could run sinatra inside an eventloop like that. legit

**Comment by seyyah** [comment]
We merge two solutions

1. [websocket-eventmachine-server](https://github.com/imanel/websocket-eventmachine-server/blob/master/examples/echo_server.rb)

2. [websocket-eventmachine-client](https://github.com/imanel/websocket-eventmachine-client/blob/master/examples/echo_client.rb)

That's ok. We runned above code successfully. No problem.

Sincerely,
seyyah
