### ISSUE TITLE
Best way to confirm connection is still subscribed?

### ISSUE THREAD

**Issue by StephenWetzel** [NullVoxPopuli/action_cable_client#16]
What is the best way to use client.subscribed? to periodically check to see if the connection is still active?

**Comment by NullVoxPopuli** [comment]
can you describe the situation in which a client would become unsubscribed?

the subscribed status is currently set to `true` if a `confirm_subscription` message is received.
https://github.com/NullVoxPopuli/action_cable_client/blob/master/lib/action_cable_client.rb#L185

what that lets us know is that the server will accept messages on whatever specified Channel.

If you want to check connection status, there is a ping sent to the client every 3 seconds.
https://github.com/NullVoxPopuli/action_cable_client/blob/master/lib/action_cable_client.rb#L169

By default, pings are not yielded to `received`, but that can be enabled by passing `true` to your `received` hook.

```ruby
#...
  client.received(true) do
    # ...
  end
#...
```

**Comment by StephenWetzel** [comment]
I noticed in development that whatever Spring does to restart the server will cause the client to become disconnected, without calling the disconnected hook.  That won't happen in production, but I'm trying to make my client be as robust as possible, and handle things like random internet connection issues.

That's interesting about the pings, thanks, I'll have to test that.  Still, I'm unsure of how to detect when the pings stop.  Sorry if this is more of an EM question, but how do I set something up that fires every minute or so and then attempts to reconnect if there hasn't been a ping in a while?

I was also just thinking of sending a message to the server and having it respond that the connection is still fine.  But again, I'm unsure of how to set that up to run periodically without an event triggering it.

**Comment by NullVoxPopuli** [comment]
yeah, I know in EM, you can set up a periodically running method.

So, 
```ruby
#...
  ping_last_received_at = false
  client.received(true) do |json|
     if client.send(:is_ping?, json)
        ping_last_received_at = Time.now
     end
    # ...
  end
  
   whatever_the_syntax_for_a_method_that_runs_every_5_seconds do
     panic if ping_is_more_than_5_seconds_old?
   end

   def ping_is_more_than_5_seconds_old?
      ping_last_received_at >= Time.now - 5.seconds
   end
#...
```

or something like that -- not tested. I just typed that right here. lol

**Comment by StephenWetzel** [comment]
Thanks, is there any way to reconnect to the server if it detects it's disconnected?  Looking at the code I don't see it.  I guess it would need a method that calls ```@_websocket_client = EventMachine::WebSocketClient.connect(_uri)``` again?  Would adding that be enough?

**Comment by NullVoxPopuli** [comment]
yeah, so there should probably be a PR that extracts the initial connect to a method.

so that you can do something like `client.connect_to_server!` or something like that.

if you want to just hack something together quickly, you could give this a go:

```ruby
    client.instance_variable_set("@_websocket_client", EventMachine::WebSocketClient.connect(client._uri))

```

**Comment by StephenWetzel** [comment]
Ok thanks, I may attempt that PR.  For now I'm trying to get it working, but I've been unable to successfully reconnect.

I added this to the main EM.run loop:
```
  EM.add_periodic_timer(10) do
    if (Time.current.to_i - latest_ping_timestamp > 10) || !client.subscribed?
      puts "#{Time.current} No recent pings"
      client.instance_variable_set("@_websocket_client", EventMachine::WebSocketClient.connect(client._uri))
      client.connected { puts "Attempting to reconnect..." }
    end
  end
```

And while it prints the output, including "Attempting to reconnect..." it doesn't actually receive any more pings.  Any ideas?

For now I may just kill the job if it detects a lack of pings, and then use a cron job to relaunch it if it's not running.

**Comment by NullVoxPopuli** [comment]
@StephenWetzel - you can check out #18, if you want to comment on it, as I believe it relates to this issue.

Maybe in a subsequent PR to #18, possible disconnection checking can be built in :-)
