### ISSUE TITLE
No message Json received when ruby client connect to rails server

### ISSUE THREAD

**Issue by HBODKR** [NullVoxPopuli/action_cable_client#17]
the ruby client connect successfully to server rails but no respond in terminal
when i stop client i have this problem :/usr/local/rvm/gems/ruby-2.2.2@global/gems/eventmachine-1.2.3/lib/eventmachine.rb:194:in `run_machine': Interrupt
        from /usr/local/rvm/gems/ruby-2.2.2@global/gems/eventmachine-1.2.3/lib/eventmachine.rb:194:in `run'
        from local_test.rb:7:in `<main>'

at terminal rails server when client ruby connect to the server this what happens :
Started GET "/cable/" for ::1 at 2017-04-20 21:09:52 +0100
Started GET "/cable/" [WebSocket] for ::1 at 2017-04-20 21:09:52 +0100
Request origin not allowed: 
Failed to upgrade to WebSocket (REQUEST_METHOD: GET, HTTP_CONNECTION: Upgrade, HTTP_UPGRADE: websocket)
Finished "/cable/" [WebSocket] for ::1 at 2017-04-20 21:09:52 +0100
2017-04-20 21:09:52 +0100: HTTP parse error, malformed request (): #<Puma::HttpParserError: Invalid HTTP format, parsing fails.>
2017-04-20 21:09:52 +0100: ENV: {"rack.version"=>[1, 3], "rack.errors"=>#<IO:<STDERR>>, "rack.multithread"=>true, "rack.multiprocess"=>false, "rack.run_once"=>false, "SCRIPT_NAME"=>"", "QUERY_STRING"=>"", "SERVER_PROTOCOL"=>"HTTP/1.1", "SERVER_SOFTWARE"=>"puma 3.8.2 Sassy Salamander", "GATEWAY_INTERFACE"=>"CGI/1.2"}
---
Started GET "/rooms/show" for ::1 at 2017-04-20 21:10:41 +0100
Processing by RoomsController#show as HTML
  Rendering rooms/show.html.erb within layouts/application
  Rendered rooms/show.html.erb within layouts/application (1.3ms)
Completed 200 OK in 608ms (Views: 568.7ms | ActiveRecord: 0.0ms)

**Comment by NullVoxPopuli** [comment]
is your repo open source?
or
can you post relevant files that will help debug this?

**Comment by HBODKR** [comment]
this for rails server : https://github.com/HBODKR/test
this for ruby client : https://github.com/HBODKR/cilent_ruby

**Comment by NullVoxPopuli** [comment]
Is there a reason you copied the gem source into your cilent_ruby project?

good news, is that I know what the problem is,

part of the problem is that you have client.perform in your EM run loop, which means that it's not waiting for the client to finish connecting.

here are some working examples: https://gist.github.com/NullVoxPopuli/edfcbbe91a7877e445cbde84c7f05b37
(complete with keyboard input)

however, the reason why puma was throwing that error was because of a missing config option.
```
config.action_cable.disable_request_forgery_protection = true
```
I had to compare your server repo with my simple action cable server https://github.com/NullVoxPopuli/mesh-relay


Here is the specific test client I used:
```ruby
require 'action_cable_client'

module KeyboardHandler
  include EM::Protocols::LineText2
  def receive_line(data)
    @client.perform('speak', message: data, to: 'user1')
  end

  def client=(client)
    @client = client
  end
end

EventMachine.run do
  client = ActionCableClient.new('ws://localhost:3000/cable?uid=user2', 'RoomChannel')
  client.connected { puts 'successfully connected.' }
  client.received do |message|
    puts message
  end

  EM.open_keyboard(KeyboardHandler){ |kb| kb.client = client }
end
```

lemme know if you have any other questions :-)

**Comment by HBODKR** [comment]
it works , thanks for you help :D

**Comment by NullVoxPopuli** [comment]
I'd like to figure out how I can get this working without disabling that option. But that's what we got to do for now.
