### ISSUE TITLE
How to close connection from client?

### ISSUE THREAD

**Issue by jasmind** [NullVoxPopuli/action_cable_client#30]
Hi,

I have written a small JRuby app and I'm using this gem to interact with rails web app Action Cable channel. I want to close the connection when I logout from the app.
Is it possible and what is the correct way to close the connection using action_cable_client gem?

Thanks

**Comment by NullVoxPopuli** [comment]
From the underlying websocket-eventmachine-client gem, yeah via https://github.com/imanel/websocket-eventmachine-client/blob/master/README.md#close

I'd gladly accept a PR that adds a more direct API for calling that method
