### ISSUE TITLE
Request origin not allowed

### ISSUE THREAD

**Issue by novneetnov** [NullVoxPopuli/action_cable_client#31]
While this gem provides a nice simple way to test out actioncable, I could not get past the initial connection. The actioncable server is not allowing any request from this client. I added the following to the application.rb file:
`config.action_cable.allowed_request_origins = [/http:\/\/*/, /https:\/\/*/]`
But still the issue persists.
Any way to get pas this issue?

**Comment by rwojnarowski** [comment]
@novneetnov you need to set this config instead:
`config.action_cable.disable_request_forgery_protection = true`

**Comment by NullVoxPopuli** [comment]
Thanks, @rwojnarowski !!! @novneetnov , does this resolve your issue?

**Comment by novneetnov** [comment]
Hey yes, thanks @rwojnarowski . That did solve my issue.
