### ISSUE TITLE
How to customize Ping messages format  from the action cable server

### ISSUE THREAD

**Issue by faisal-bhatti** [NullVoxPopuli/action_cable_client#6]
As Action Cable send a ping like 
{ "type" => "ping", "message" => 1461845503 }

but it is not the standard format. There should be an opcode against the 'type' key.  So how to customize it.

**Comment by NullVoxPopuli** [comment]
`action_cable_client` filters out pings, are you wanting to process them?
as far as customizing the actual ping message, that would be up to https://github.com/rails/rails/tree/master/actioncable

**Comment by NullVoxPopuli** [comment]
Closing due to age
