### ISSUE TITLE
Cannot connect with Rails 5.0.0.1 actioncable-example

### ISSUE THREAD

**Issue by abigoroth** [NullVoxPopuli/action_cable_client#8]
I am trying to connect this client to `https://github.com/rails/actioncable-examples` but the client didn't response anything.

![image](https://cloud.githubusercontent.com/assets/520990/21301924/bd43294a-c5ec-11e6-833e-a95a70728b41.png)
it just forever silence.

below is my code, i'm using authetication token instead of session which i tested fine from the web browser.

```ruby
require 'action_cable_client'

EventMachine.run do
  uri = "ws://localhost:28080/?auth_token=aaa"
  client = ActionCableClient.new(uri, 'CommentsChannel')
  client.connected { puts 'successfully connected.' }
  client.received do | message |
    puts message
  end
  client.perform('follow', { message_id: 1 })
end
```

noticed that `client.perform('follow', { message_id: 1 })` is what i'm trying to simulate from the `actioncable-examples` app `@perform 'follow', message_id: messageId` in comments.coffee. I don't think it's the right code. :)

Update :
I notice that server quickly disconnect me when I implement this code `client.disconnected { puts 'DISCONNECTED' }` it disconnects right away after I started this client.

**Comment by NullVoxPopuli** [comment]
Re: the disconnect, it looks like the server is disconnecting everyone when it receives a message. 

Also, it looks like, on the server, you need a preexisting stream to follow? So that's why you're not receiving anything.

**Comment by NullVoxPopuli** [comment]
I think I was wrong about stream_from (it's been a while since I worked with ActionCable). Checkout these docs: http://www.rubydoc.info/github/rails/actioncable/ActionCable%2FChannel%2FStreams%3Astream_from

looks like stream_from is just for naming a stream.

For an example for sending stuff back to a client, checkout this app: https://github.com/NullVoxPopuli/mesh-relay/blob/master/app/channels/mesh_relay_channel.rb

Also, that disconnect thing you reported miiiiight be a bug... will need some further investigation. (I noticed that my AC Server also has stop_all_streams, but only on the subscribed hook. hmm.

**Comment by NullVoxPopuli** [comment]
Also, have you seen these examples? https://gist.github.com/NullVoxPopuli/edfcbbe91a7877e445cbde84c7f05b37

**Comment by emanzx** [comment]
Hi, I test https://gist.github.com/NullVoxPopuli/edfcbbe91a7877e445cbde84c7f05b37 seem like it works ok even with latest rails 5.. btw is there anyway to make the client to be able to connect to wss(websocket with ssl) ?

**Comment by NullVoxPopuli** [comment]
@emanzx is there an issue with `wss://` urls? if so, could you open a new issue?

**Comment by emanzx** [comment]
I think em-websocket mentioned well in their description about still there is no support for wss:

**Comment by NullVoxPopuli** [comment]
is this the error you're getting? https://github.com/igrigorik/em-websocket/issues/142

**Comment by NullVoxPopuli** [comment]
have you seen this part of the docs? https://github.com/igrigorik/em-websocket#secure-server

It looks like `action_cable_client` needs to support those options.

I'll gladly accept a PR :-)

**Comment by NullVoxPopuli** [comment]
closing -- feel free to open another issue if there are still questions

**Comment by NullVoxPopuli** [comment]
@emanzx master is soon to be able to use ssl - see #20

**Comment by abigoroth** [comment]
awesome! cant wait for this ssl feature!

**Comment by NullVoxPopuli** [comment]
It's merged and released, if you want to give it a shot

**Comment by emanzx** [comment]
wow.. nice work @NullVoxPopuli excited to test this..
